repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the latest version
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 23.9.1  # Use the latest version
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.13.1  # Use the latest version
  hooks:
  - id: isort

# - repo: https://gitlab.com/pycqa/flake8
#   rev: '4.0.1'  # Use the latest version
#   hooks:
#   - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.950'  # Use the latest version
  hooks:
  - id: mypy

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.1'  # Use the latest version
  hooks:
  - id: bandit

# Optional hooks based on your project needs

# - repo: https://github.com/pre-commit/mirrors-pydocstyle
#   rev: '6.1.1'  # Use the latest version
#   hooks:
#   - id: pydocstyle

# - repo: https://github.com/codespell-project/codespell
#   rev: v2.1.0  # Use the latest version
#   hooks:
#   - id: codespell
#     args: ['--ignore-words-list', 'ba,fo,foe,te']
