name: game
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bullet-cpp=3.24
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - faiss-cpu=1.7.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libfaiss=1.7.4
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libsqlite=3.43.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - ncurses=6.4
  - numpy-base=1.26.2
  - openssl=3.1.4
  - pip=23.2.1
  - pthread-stubs=0.4
  - pybullet=3.24
  - python=3.10.12
  - python_abi=3.10
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.41.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - pip:
      - async-timeout==4.0.3
      - beautifulsoup4==4.12.2
      - bokeh==2.4.3
      - build==1.0.3
      - cachecontrol==0.13.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.1
      - cleo==2.1.0
      - contourpy==1.1.1
      - crashtest==0.4.1
      - cryptography==41.0.3
      - cycler==0.12.1
      - cython==3.0.4
      - distlib==0.3.7
      - dulwich==0.21.6
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - gdown==4.7.1
      - identify==2.5.33
      - idna==3.4
      - imageio==2.31.6
      - importlib-metadata==6.8.0
      - installer==0.7.0
      - jaraco-classes==3.3.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - keyring==24.2.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - more-itertools==10.1.0
      - msgpack==1.0.7
      - networkx==3.2.1
      - nodeenv==1.8.0
      - numpy==1.25.2
      - opencv-python==4.8.0.76
      - packaging==23.2
      - pexpect==4.8.0
      - pillow==10.0.1
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - plotly==5.18.0
      - poetry==1.7.0
      - poetry-core==1.8.1
      - poetry-plugin-export==1.6.0
      - pre-commit==3.6.0
      - ptyprocess==0.7.0
      - pybind11==2.11.1
      - pycparser==2.21
      - pygame==2.5.2
      - pyopengl==3.1.7
      - pyopengl-accelerate==3.1.7
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - rapidfuzz==3.5.2
      - redis==5.0.1
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - shellingham==1.5.4
      - six==1.16.0
      - soupsieve==2.5
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tomli==2.0.1
      - tomlkit==0.12.2
      - tornado==6.3.3
      - tqdm==4.66.1
      - trove-classifiers==2023.10.18
      - typing-extensions==4.8.0
      - urllib3==2.0.7
      - virtualenv==20.24.6
      - vis-nav-game==1.1.2
      - xattr==0.10.1
      - zipp==3.17.0
      - zmq==0.0.0
